// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQZecnOWiJOL-z2jNKXM459yivGDhLskU',
    appId: '1:1040276065383:web:2ca84386ba68a6ab72d8c2',
    messagingSenderId: '1040276065383',
    projectId: 'arwayz-c30b3',
    authDomain: 'arwayz-c30b3.firebaseapp.com',
    storageBucket: 'arwayz-c30b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL9WXVfKWNKe8uJb3MLbpo1p80gKvE-Js',
    appId: '1:1040276065383:android:aed5c084cd9a098172d8c2',
    messagingSenderId: '1040276065383',
    projectId: 'arwayz-c30b3',
    storageBucket: 'arwayz-c30b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp9d1PaEPAE70k52-0x6ib0RovTc4qaGE',
    appId: '1:1040276065383:ios:451c9a9c8738914a72d8c2',
    messagingSenderId: '1040276065383',
    projectId: 'arwayz-c30b3',
    storageBucket: 'arwayz-c30b3.firebasestorage.app',
    iosBundleId: 'com.example.arwayz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp9d1PaEPAE70k52-0x6ib0RovTc4qaGE',
    appId: '1:1040276065383:ios:451c9a9c8738914a72d8c2',
    messagingSenderId: '1040276065383',
    projectId: 'arwayz-c30b3',
    storageBucket: 'arwayz-c30b3.firebasestorage.app',
    iosBundleId: 'com.example.arwayz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQZecnOWiJOL-z2jNKXM459yivGDhLskU',
    appId: '1:1040276065383:web:565d8c371b44b04772d8c2',
    messagingSenderId: '1040276065383',
    projectId: 'arwayz-c30b3',
    authDomain: 'arwayz-c30b3.firebaseapp.com',
    storageBucket: 'arwayz-c30b3.firebasestorage.app',
  );
}
